title: Bridging Mental Health Network
url: "https://bridgingmentalhealth.github.io"
baseurl: ""  
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - Events.md
  - Members.md
  - Videos.md
  - External.md
